"""
Generate supabase/raw_seed.sql from the UNTOUCHED original database
(data/Risk_and_compliance_dummy_dataset.db). Emits the 6 source tables as
raw_<table> so the board can explore the delivered data BEFORE cleaning:

  - every column typed text and NO primary/foreign keys — the raw data has
    duplicate ids and untyped values; this is the pre-cleaning state,
  - values preserved verbatim (empty strings, whitespace, mixed casing) so the
    EDA identifies the quality issues live rather than trusting the log,
  - RLS on, SELECT-only for anon/authenticated — same policy as the clean layer.

Run from the repo root: python supabase/generate_raw_seed.py
"""
import sqlite3
import math

OUT = "supabase/raw_seed.sql"
BATCH = 200
SRC = "data/Risk_and_compliance_dummy_dataset.db"
TABLES = ["customers", "accounts", "transactions",
          "compliance_alerts", "sanctions_screening", "chargebacks"]


def raw_literal(v):
    # Preserve dirty values verbatim: only a true SQL NULL becomes NULL. Empty
    # strings, whitespace and casing are kept so the EDA can surface them.
    if v is None or (isinstance(v, float) and math.isnan(v)):
        return "NULL"
    return "'" + str(v).replace("'", "''") + "'"


def rls(table):
    return [
        f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY;",
        f"REVOKE INSERT, UPDATE, DELETE, TRUNCATE ON {table} FROM anon, authenticated;",
        f'CREATE POLICY "{table}_read_only" ON {table} '
        "FOR SELECT TO anon, authenticated USING (true);",
    ]


con = sqlite3.connect(SRC)
con.row_factory = sqlite3.Row
parts = ["-- Generated by supabase/generate_raw_seed.py — do not edit by hand.",
         "-- Raw source tables (pre-cleaning): all text, no keys, RLS SELECT-only.",
         ""]
counts = {}
for t in TABLES:
    raw_t = f"raw_{t}"
    cols = [r[1] for r in con.execute(f"PRAGMA table_info({t})")]
    parts.append(f"DROP TABLE IF EXISTS {raw_t} CASCADE;")
    coldef = ",\n  ".join(f"{c} text" for c in cols)
    parts.append(f"CREATE TABLE {raw_t} (\n  {coldef}\n);")
    parts.append("")
    rows = con.execute(f"SELECT * FROM {t}").fetchall()
    counts[raw_t] = len(rows)
    collist = ", ".join(cols)
    for start in range(0, len(rows), BATCH):
        chunk = rows[start:start + BATCH]
        values = ",\n".join(
            "(" + ", ".join(raw_literal(r[c]) for c in cols) + ")" for r in chunk)
        parts.append(f"INSERT INTO {raw_t} ({collist}) VALUES\n{values};")
    parts.append("")
    parts += rls(raw_t) + [""]

with open(OUT, "w", encoding="utf-8") as f:
    f.write("\n".join(parts))

print(f"Wrote {OUT}: " + ", ".join(f"{k}={v}" for k, v in counts.items()))
